### ISSUE TITLE
initializing codeblock object slow

### ISSUE THREAD

**Issue by frazahod** [tmr232/Sark#44]
I am iterating through a list of addresses and colors for functions, lines, and codeblocks. I use identical code for each with the only difference being whether sark.Function(address)/sark.Line(address) is called or sark.CodeBlock(address). The issue is that when called on my test files the line and function loops take only .05 seconds. The loop that calls codeblock takes 6.5 and has dramatically decreased the speed of my program.

**Comment by tmr232** [comment]
This is due to the way a codeblock is generated. It currently needs to:
1. Get a flowchart for the containing function
1. Iterate over the flowchart to find the block

And doing this for every address takes a while. I will look into that and see what I can do.

**Comment by frazahod** [comment]
I suspected that it was something like that. Thanks for getting back so
quickly, and thank you for creating this tool. It has certainly made my
life easier.

**Comment by tmr232** [comment]
Thanks for the feedback :smile: 

Coming up with a proper solution might take me a while (as I don't like the idea of caching results, and am not sure that there is an alternative here), but you can probably find a simple solution for your needs.

My approach (not knowing exactly what your requirements are) would be to iterate over all functions using `sark.functions()`, get the flowcharts using `sark.FlowChart(function)`, and then iterating the blocks using `for block in flowchart`. This should (hopefully) be a lot faster. I hope this suits your needs.

**Comment by frazahod** [comment]
All right, I will implement that and let you know. Thanks.

**Comment by frazahod** [comment]
So I took your advice and used this

def gen_block_dict(self):
    block_dict = {}
    for func in sark.functions():
        flow_chart = sark.FlowChart(func.ea)
        for block in flow_chart:
            block_dict[block.startEA] = block
    return block_dict


which decreased the time it took by a factor of 50!

previously I had called

sark.CodeBlock(EA)

which was modified to

b_dict = self.gen_block_dict()

sblock = b_dict[EA]



Anyway, may I suggest that you add a blocks() function similar to the
lines() and function() functions?

Thanks
Fraser Hood

**Comment by tmr232** [comment]
I began to implement the function, and found a much better solution.

Just use `sark.FlowChart(bounds=(start, end))`. It gives a flowchart with every block in the range. Fast and easy. It will also include non-function blocks, so be aware of that.

This is actually really cool, I'm happy to have come across it.

I will add it to Sark, though.

**Comment by tmr232** [comment]
Added the function in https://github.com/tmr232/Sark/tree/codeblocks, let me know if it works for you.

**Comment by frazahod** [comment]
thanks

**Comment by frazahod** [comment]
So i implemented it like so:

for block in sark.codeblocks():
    print block.color
    block_dict[block.startEA] = block

and what I found is that the block.color is always None, but it picks up
the line colors

for block in sark.codeblocks():
    print block.color
    block_dict[block.startEA] = block
    for line in block.lines:
        print line.color
        block_dict[line.ea] = block

just fine. Let me know if I am implementing this wrong.

**Comment by tmr232** [comment]
Block color and line color are two different things. You can see the implementation here - https://github.com/tmr232/Sark/blob/master/sark/codeblocks.py#L44

What are you trying to do?

**Comment by frazahod** [comment]
No I realize that. The issue is that one of my blocks is colored, and yet
the print block.color statement never prints anything other than None.

**Comment by frazahod** [comment]
I brought up the lines because they are printing the color as I would
expect them to.

**Comment by frazahod** [comment]
So to clarify, this

for func in sark.functions():
    flow_chart = sark.FlowChart(func.ea)
    for block in flow_chart:
        print block.color

prints out the color that I expect, where as

for block in sark.codeblocks():
    print block.color

this does not.

**Comment by tmr232** [comment]
Is the color of the block set in the graph view? If it is, it sounds like a bug in the color extraction.

**Comment by frazahod** [comment]
Yes it is.

**Comment by tmr232** [comment]
Can you show a screenshot of the graph overview?
And which version of IDA are you using?

**Comment by frazahod** [comment]
Sorry to bother you, but I was wondering if there was any news on the issue.

**Comment by tmr232** [comment]
OK, solved it.
You need to use the function's flowchart, and not just any chart. Should work now. I wonder how it affects performance.

**Comment by frazahod** [comment]
I will let you know.

**Comment by frazahod** [comment]
So I am still having a similar issue albeit not exactly the same. The
codeblock colors are not updating properly but the line colors are. That
is, if I set a codeblock to lime green (#00ff00) save that information and
then set it back to white, when I try to change it back to green from the
saved info, it changes the line colors (is what it looks like) to green but
the codeblock stays as white. Ill include some pics to illustrate.

**Comment by tmr232** [comment]
Can you also say what version of IDA are you using? And on which OS?

**Comment by frazahod** [comment]
Version 6.9.160222 (64-bit)
Windows 10

**Comment by tmr232** [comment]
Same for me, and the new blocks code seems to work. Weird.

**Comment by frazahod** [comment]
Yeah I noticed that it seemed like it was retrieving the colors correctly
when I printed it out.

**Comment by tmr232** [comment]
So are there any remaining issues, or can I consider it solved?

**Comment by frazahod** [comment]
Ill let you know. Been really busy.

**Comment by frazahod** [comment]
Works great! Awesome!
